[package]
name = "libprio-rs"
version = "0.1.0"
authors = ["Josh Aas <jaas@kflag.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
