name: ci-build

on:
  push:
    branches: [ main, release/** ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: cargo fmt --message-format human -- --check

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docs
      run: cargo doc --all-features
      env:
        RUSTDOCFLAGS: -Dwarnings

  build-binaries:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --package prio-binaries
    - name: Clippy
      run: cargo clippy --package prio-binaries

  build-crate:
    strategy:
      matrix:
        features: [
          "--no-default-features",
          "--all-features",
          "--features=default",
          "--features=test-util",
          "--features=multithreaded",
          "--features=test-util,multithreaded",
          "--features=prio2",
          "--features=prio2,test-util",
          "--features=prio2,multithreaded",
          "--features=prio2,test-util,multithreaded",
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy --workspace --all-targets ${{ matrix.features }}
    - name: Build crate
      run: cargo build --verbose --package prio ${{ matrix.features }}
    - name: Run tests
      run: cargo test --verbose ${{ matrix.features }}
    - name: Build benchmarks
      run: cargo bench --no-run ${{ matrix.features }}
