name: ci-build

on:
  push:
    branches: [ main, release/** ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    strategy:
      matrix:
        features: [
          "--all-features",
          "--features=default",
          "--features=test-vector",
          "--features=multithreaded",
          "--features=test-vector,multithreaded",
          "--features=prio2",
          "--features=prio2,test-vector",
          "--features=prio2,multithreaded",
          "--features=prio2,test-vector,multithreaded",
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: cargo fmt --message-format human -- --check
    - name: Clippy
      run: cargo clippy --workspace --all-targets ${{ matrix.features }}
    - name: Docs
      run: cargo doc --all-features
      env:
        RUSTDOCFLAGS: -Dwarnings
    - name: Build
      run: cargo build --verbose --workspace ${{ matrix.features }}
    - name: Run tests
      run: cargo test --verbose ${{ matrix.features }}
    - name: Build benchmarks
      run: cargo bench --no-run ${{ matrix.features }}
